### ISSUE TITLE
When will the code of Lampilot be available

### ISSUE THREAD

**Issue by hairuoliu1** [IrohXu/Awesome-Multimodal-LLM-Autonomous-Driving#1]

**Comment by IrohXu** [comment]
@maysonma will release it soon.

**Comment by maysonma** [comment]
> @maysonma will release it soon.

Hi Hairuo, thank you for your interest in our research. We are still refining our work and will release the code before CVPR, once everything is finalized.

**Comment by hairuoliu1** [comment]
Looking forward to it. @maysonma
